package main

// assets-data is generated by: `go-bindata -debug -o assets-data.go -prefix assets assets/`

import (
	"net/http"
	"strings"
	"bytes"
	"time"
)

func assets(w http.ResponseWriter, req *http.Request) {
	path := strings.TrimPrefix(req.URL.Path, "/assets/")
	data, err := Asset(path)

	if err != nil {
		http.NotFound(w, req)
	} else  {
		http.ServeContent(w, req, path, time.Unix(0, 0), bytes.NewReader(data))
	}
}

func assetPath(asset string) string {
	return "/assets/" + asset
}
