package main

// assets-data is generated by: `go-bindata -debug -o assets-data.go -prefix assets assets/`

import (
  "net/http"
  "io/ioutil"
  "encoding/json"
)

var assetMap map[string]string

func initAssets() {
  assetMapJson, err := ioutil.ReadFile("assets-hashed/fileMap.json")
  checkError(err)

  assetMap = make(map[string]string)
  checkError(json.Unmarshal(assetMapJson, &assetMap))
}


func assetsHandler() http.Handler {
  return http.StripPrefix("/assets/", http.FileServer(http.Dir("assets-hashed")))
}

func assetPath(asset string) string {
  return assetMap[asset]
}
